settings:
# :: List of blocks
  blocks:
# :: Minecraft block name, Example: minecraft:log without minecraft
    log:
# :: List of drops
# ::
# :: The chance system in the plugin is the simplest, I ask you to put the minimum chance of falling out first
# :: Id -> Identifier of the item that will fall out when breaking this block
# :: Percent -> The chance of this resource falling out of the block
# ::
      drops:
        0:
          id: 5
          percent: 5.0
          count: 1
        1:
          id: 5
          percent: 25.0
          count: 2
        2:
          id: 5
          percent: 99.0
          count: 4
    stone:
      drops:
        0:
          id: 4
          percent: 100.0
          count: 1
    cobblestone:
      drops:
        0:
          id: 4
          percent: 100.0
          count: 1
    coal_ore:
      drops:
        0:
          id: 263
          percent: 3.0
          count: 3
        1:
          id: 263
          percent: 8.0
          count: 2
        2:
          id: 263
          percent: 100.0
          count: 1
    iron_ore:
      drops:
        0:
          id: 265
          percent: 1.0
          count: 3
        1:
          id: 265
          percent: 3.0
          count: 2
        2:
          id: 265
          percent: 100.0
          count: 1
    gold_ore:
      drops:
        0:
          id: 266
          percent: 1.0
          count: 3
        1:
          id: 266
          percent: 3.0
          count: 2
        2:
          id: 266
          percent: 100.0
          count: 1
    diamond_ore:
      drops:
        0:
          id: 264
          percent: 1.0
          count: 2
        1:
          id: 264
          percent: 100.0
          count: 1
    emerald_ore:
      drops:
        0:
          id: 388
          percent: 1.0
          count: 3
        1:
          id: 388
          percent: 100.0
          count: 1
